/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.CellBusters;
import Model.BMP;
import Model.MatrizPixel;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.File;
import java.io.IOException;
import java.io.RandomAccessFile;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @Autores: Samuel Blum Vorpagel - Rafael Fiori Kruger
 */
public class OPLogicasControlador extends javax.swing.JFrame {

    private ArrayList<JanelaImgs> listaImagens;
    private JFImagem parent;
    private int counter;

    /**
     * Creates new form OPLogicasControlador
     */
    public OPLogicasControlador(JFImagem parentComponent) {
        initComponents();
        buttonGroup1.add(opAND);
        buttonGroup1.add(opOR);
        buttonGroup1.add(opXOR);
        listaImagens = new ArrayList<JanelaImgs>();
        parent = parentComponent;
        counter = 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        botaoAbrir = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaoAplicaOpe = new javax.swing.JButton();
        Caixa1 = new javax.swing.JComboBox();
        Caixa2 = new javax.swing.JComboBox();
        opAND = new javax.swing.JRadioButton();
        opOR = new javax.swing.JRadioButton();
        opXOR = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operações Lógicas");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                OPLogicasControlador.this.windowClosed(evt);
            }
        });

        botaoAbrir.setText("Abrir Imagem...");
        botaoAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAbrirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel1.setText("Imagem 1");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Imagem 2");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel3.setText("Operação");

        botaoAplicaOpe.setText("Aplicar Operação");
        botaoAplicaOpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAplicaOpeActionPerformed(evt);
            }
        });

        Caixa1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Caixa1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma imagem..." }));

        Caixa2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        Caixa2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma imagem..." }));

        opAND.setText("AND");

        opOR.setText("OR");

        opXOR.setText("XOR");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(opAND)
                                    .addComponent(opOR))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(opXOR)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(botaoAplicaOpe, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel1)
                                            .addComponent(Caixa1, 0, 220, Short.MAX_VALUE))
                                        .addGap(33, 33, 33)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(Caixa2, 0, 220, Short.MAX_VALUE))))
                                .addGap(37, 37, 37))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(botaoAbrir, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoAbrir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Caixa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Caixa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(opAND)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(opOR)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoAplicaOpe)
                    .addComponent(opXOR))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void botaoAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAbrirActionPerformed
        JFileChooser arquivo = new JFileChooser();
        int retorno = arquivo.showOpenDialog(null);
        BMP bmp = null;
        if (retorno == arquivo.APPROVE_OPTION) {
            String nomeImg;
            try {
                File f = arquivo.getSelectedFile();
                RandomAccessFile rf = new RandomAccessFile(f, "r");
                byte[] b = new byte[(int) rf.length()];
                rf.read(b);
                rf.close();
                bmp = new BMP(b);
            } catch (IOException ex) {
                Logger.getLogger(CellBusters.class.getName()).log(Level.SEVERE, null, ex);
            }

            nomeImg = arquivo.getSelectedFile().getName();
            JanelaImgs jal = new JanelaImgs(bmp, this, counter);
            int ct = 0;
            for (int i = 0; i < listaImagens.size(); i++) {
                if (listaImagens.get(i).getName().equals(nomeImg)) {
                    ct++;
                }
            }
            if (ct > 0) {
                boolean flag = false;
                String nomeAux = nomeImg;
                nomeImg = nomeImg + " (" + ct + ")";
                for (int i = 0; i < listaImagens.size(); i++) {
                    if (listaImagens.get(i).getTitle().equals(nomeImg)) {
                        flag = true;
                    }
                }
                if (flag) {
                    nomeAux = nomeAux + " (" + (ct + 1) + ")";
                    jal.setTitle(nomeAux);
                    Caixa1.addItem(nomeAux);
                    Caixa2.addItem(nomeAux);
                } else {
                    jal.setTitle(nomeImg);
                    Caixa1.addItem(nomeImg);
                    Caixa2.addItem(nomeImg);
                }
            } else {
                jal.setTitle(nomeImg);
                Caixa1.addItem(nomeImg);
                Caixa2.addItem(nomeImg);
            }
            jal.setName(nomeImg);
            jal.getImagem().setImagem(bmp);
            jal.getImagem().reset();
            jal.getImagem().update();
            jal.setVisible(true);
            listaImagens.add(jal);
            counter++;
        }
    }//GEN-LAST:event_botaoAbrirActionPerformed

    private void botaoAplicaOpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoAplicaOpeActionPerformed
        if (Caixa1.getSelectedIndex() != 0) {
            if (Caixa2.getSelectedIndex() != 0) {
                if (buttonGroup1.getSelection() != null) {
                    BMP b1, b2, aux;
                    String nome1, nome2;
                    int index1 = Caixa1.getSelectedIndex() - 1;
                    int index2 = Caixa2.getSelectedIndex() - 1;
                    b1 = listaImagens.get(index1).getImagem().getImagem();
                    b2 = listaImagens.get(index2).getImagem().getImagem();
                    nome1 = listaImagens.get(index1).getTitle();
                    nome2 = listaImagens.get(index2).getTitle();
                    
                    /* A abordagem nas próximas 2 linhas de código realiza a 
                     * cópia do conteúdo da variável "b1", ao invés de obter  
                     * sua referência. Isto é feito para evitar 
                     * que as alterações feitas na variável "aux" sejam 
                     * espelhadas para a variável "b1", que por sua vez é uma
                     * referência para uma imagem contida na lista. */
                    byte[] copia = b1.getTudo().clone();
                    aux = new BMP(copia); 
                    //
                    
                    String titulo;
                    if (opAND.isSelected()) {
                        aux.getMp().opAND(b2.getMp());
                        titulo = nome1 + " AND " + nome2;
                    } else {
                        if (opOR.isSelected()) {
                            aux.getMp().opOR(b2.getMp());
                            titulo = nome1 + " OR " + nome2;
                        } else {
                            aux.getMp().opXOR(b2.getMp());
                            titulo = nome1 + " XOR " + nome2;
                        }
                    }
                    JanelaImgs jal = new JanelaImgs(aux, this, counter);
                    jal.setTitle(titulo);
                    jal.getImagem().setImagem(aux);
                    jal.getImagem().reset();
                    jal.getImagem().update();
                    jal.setVisible(true);
                    listaImagens.add(jal);
                    Caixa1.addItem(titulo);
                    Caixa2.addItem(titulo);
                    counter++;
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Selecione a operação", null, JOptionPane.ERROR_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(rootPane, "Selecione a imagem 2", null, JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Selecione a imagem 1", null, JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botaoAplicaOpeActionPerformed

    private void windowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_windowClosed
        parent.setOPLogicasAberto();
    }//GEN-LAST:event_windowClosed

    public void excluirElementoLista(int num_id) {
        for (int i = 0; i < listaImagens.size(); i++) {
            if (num_id == listaImagens.get(i).getId()) {
                listaImagens.remove(i);
                counter--;
                Caixa1.removeItemAt(i + 1);
                Caixa2.removeItemAt(i + 1);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OPLogicasControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OPLogicasControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OPLogicasControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OPLogicasControlador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OPLogicasControlador(null).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Caixa1;
    private javax.swing.JComboBox Caixa2;
    private javax.swing.JButton botaoAbrir;
    private javax.swing.JButton botaoAplicaOpe;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JRadioButton opAND;
    private javax.swing.JRadioButton opOR;
    private javax.swing.JRadioButton opXOR;
    // End of variables declaration//GEN-END:variables
}
